development:
  adapter: postgresql
  database: noted
  host: localhost
  username: postgres
  password: root

#   test:
#   adapter: postgresql
#   database: noted_database_test
#   pool: 5
#   timeout: 5000

# production:
#   adapter: postgresql
#   database: noted_database_production
#   pool: 5
#   timeout: 5000